library(reshape2)
library(dplyr)
library(ggplot2)

get_logit_details <- function(actual_values, predicted_values, prediction_threshold){
  preds <- ifelse(predicted_values > prediction_threshold, 1, 0)
  tab <- table(actual_values, preds)
  print(tab)
  CCR <- c("CCR", sum(diag(tab))/sum(tab))
  false_positive <- c("False Positive", tab[1,2]/sum(tab[1,]))
  false_negative <- c("False Negative", tab[2,1]/sum(tab[2,]))
  spec <- c("Specificity", tab[1,1] / sum(tab[1,]))
  sensitivity <- c("Sensitivity", tab[2,2]/sum(tab[2,]))
  prec <- tab[2,2]/sum(tab[,2])
  rec <- tab[2,2]/sum(tab[2,])
  precision <- c("Precision", prec)
  recall <- c("Recall", rec)
  f_score <- c("F score", 2*(prec*rec)/(prec + rec))
  print(CCR)
  print(false_positive)
  print(false_negative)
  print(spec)
  print(sensitivity)
  print(precision)
  print(recall)
  print(f_score)
  return (data.frame(CCR, spec, sensitivity, precision, recall, false_positive, false_negative, f_score, tab))
}
